### ISSUE TITLE
Cant install diamond rpm on centos 7 => Requires: python(abi) = 2.6

### ISSUE THREAD

**Issue by amitgilad3** [python-diamond/Diamond#157]
when i try to install diamond rpm with yum install i get the following error
  python(abi) = 2.6 is needed by diamond-4.0.128-0.noarch.rpm

running environment:
centos 7
python 2.7.5

is there any way i can build the rpm and tell the requirements is  python(abi) >= 2.6 ??

**Comment by mrh666** [comment]
Same here, Centos 7 with python 7 and the the error the same: 
$ python(abi) = 2.6 is needed by diamond-4.0.128-0.noarch.rpm

If I create rpm on Centos 7 (python 2.7) they doesn't work on Centos 6 and opposite situation the same.
So is there is any way to manage python >= SOME_VERSION?

**Comment by DStape** [comment]
Hello @amitgilad3, @mrh666,

I'm unable to repro this issue using the latest centos 7 docker image and following the instructions at https://diamond.readthedocs.io/en/latest/Getting-Started/Installation/.

Therefore, due to the above and because this issue is just under 3 years old, this issue will be closed (@josegonzalez ).

Please feel free to open a new issue if you still see this or another issue, thanks.
