### ISSUE TITLE
Version tags are missing

### ISSUE THREAD

**Issue by docwhat** [python-diamond/Diamond#195]
The last version tag in the git repository is `v4.0.0`... All the tags up to and including `v4.0.41` are missing.

**Comment by josegonzalez** [comment]
@kormoc This is probably something you are best to handle?

**Comment by bmhatfield** [comment]
Only major versions are tagged. The build script counts the number of commits from the last major version and appends that to the tag value. Individual version tags have never been added to this repo, AFAIK.

**Comment by josegonzalez** [comment]
We should add individual version tags going forward though?

**Comment by runejuhl** [comment]
I wouldn't mind seeing version tags on more versions. I just tried out v4.0, (naïvely) assuming it was the latest stable, and ran into a a bug when `classes.py` tries to infer the class name. It's since been fixed (https://github.com/python-diamond/Diamond/pull/47/files#diff-264916192cc0a7d2ccfa0c62630b34e7L66), but I would have loved to not spend a few hours going through an unfamiliar codebase to fix what turned out to have been fixed 6 months ago :)
