### ISSUE TITLE
Time in queue for RabbitMQ collector

### ISSUE THREAD

**Issue by tkirill** [python-diamond/Diamond#279]
Hi!  Could you tell please is it possible to report time a message spent in queue?  That is time between publish and ack?

**Comment by DStape** [comment]
Hello @tkirill,

We're trying to prune the backlog of open issues - since this ticket was opened >2.5 years ago and because the question asked is not specifically about diamond, we're going to close this off.

(Perhaps https://github.com/rabbitmq/rabbitmq-message-timestamp will allow you to retrieve the info you're looking for.)

**Comment by shortdudey123** [comment]
Closing per previous comment.
