### ISSUE TITLE
How to set my metric path when creating a custom collector?

### ISSUE THREAD

**Issue by ersiko** [python-diamond/Diamond#584]
Hi

I'm trying to create my own collector, but I'm having problems with the path. The collector is called "MyCustomCollector" and the code is as simple as:
```
import diamond.collector

class MyCustomCollector(diamond.collector.Collector):
    def collect(self):
        metric_name = "my_test"
        metric_value = 42
        self.publish(metric_name, metric_value)
```
I expected to find the metric at servers.hostname.my_test, but it's being written to servers.hostname.MyCustomCollector.my_test. There's nothing about setting the metric path on the ExampleCollector documentation, so I'm not sure how to change that.

Any hint?

Thanks!

**Comment by shortdudey123** [comment]
You need to set the config option of `path` to `''` however, this is generally not a good idea since you end up with a large number of metrics at the same level.  You should set `path` to a name that easily identities your collector

See https://github.com/python-diamond/Diamond/blob/master/src/collectors/ntp/ntp.py#L52

**Comment by ersiko** [comment]
Thanks! I created a PR adding that information to the ExampleCollector, hoping the next person will have it a bit easier :)
