### ISSUE TITLE
ERROR: diamond requires Python '==2.7' but the running Python is 2.7.16

### ISSUE THREAD

**Issue by SiqingYu** [python-diamond/Diamond#731]
Environment: Ubuntu 19.04

I am trying to set up the environment as instructed by *The Hitchhiker's Guide to Python*:

```
$ git clone https://github.com/python-diamond/Diamond.git
$ virtualenv -p python2 venv  # It's not Python 3 compatible yet...
$ source venv/bin/activate
(venv)$ cd Diamond/
(venv)$ pip install --editable .
```

Then `pip` throws out an error:
```
ERROR: diamond requires Python '==2.7' but the running Python is 2.7.16
```

**Comment by dienhoa** [comment]
Hi. I'm getting the same error as you while following the book.

The problem seems can be fixed by editing in setup.py at setup()

from 
`python_requires='==2.7`
to your specific version of python (in your case 2.7.16)
`python_requires='==2.7.16'`

To run the test I also need to install: `pip install redis`

Hope that helps,
